language: node_js
node_js:
- '6'
- '7'
- '8'
sudo: false
cache:
  directories:
  - node_modules
services:
- mongodb
install:
- npm install
deploy:
  provider: npm
  email: system@coorpacademy.com
  api_key:
    secure: FsBzRST66ph8B8BR/z7q7FiNtmK5BspeYhxJL3WKuqt//vTwZH4v/A9IaitLkDs1WIK6SoXC2yY0tunGZeXiQjg/gp/593g5cUBBkvItcbA4LHuH9u+QWNQMNSTqlKDArHhVyO6badTEV0KxvfoU6VtFTQBTYf2L19WpS8/LdxI=
  on:
    tags: true
    repo: CoorpAcademy/mongo-fixme
